version: '3.8'

services:
  # Banco de Dados - Coração da persistência do ZeroCore
  db:
    image: postgres:16-alpine
    container_name: zerocore_db
    restart: always
    environment:
      POSTGRES_USER: user_zerocore      # <--- O Banco espera este usuário
      POSTGRES_PASSWORD: password_zerocore
      POSTGRES_DB: zerocore_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend - API robusta em FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: zerocore_api
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      # CORREÇÃO AQUI: Atualizado para bater com as credenciais do serviço 'db' acima
      # Formato: postgresql://USUARIO:SENHA@HOST:PORTA/NOME_BANCO
      - DATABASE_URL=postgresql://user_zerocore:password_zerocore@db:5432/zerocore_db
      
      # Configurações do AD (Mantenha as suas)
      - AD_SERVER=ldap://192.168.0.31
      - AD_DOMAIN=mdr.local
      - AD_BASE_DN=DC=mdr,DC=local
      - AD_BIND_USER=svc_zerocore@mdr.local  
      - AD_BIND_PASSWORD=mdr.12345    
    depends_on:
      - db

  # Frontend - Interface Next.js Responsiva
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: zerocore_web
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data: